# ---------------
# It is just used to test it in OLM before it be published
# ---------------
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: postgresql-operatorgroup
  namespace: marketplace
spec:
  targetNamespaces:
    - marketplace