apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgresql-operator
  template:
    metadata:
      labels:
        name: postgresql-operator
    spec:
      serviceAccountName: postgresql-operator
      containers:
        - name: postgresql-operator
          # Replace this with the built image name
          image: dev4devscom/postgresql-operator:master
          command:
          - postgresql-operator
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 60m
              memory: 128Mi
            requests:
              cpu: 30m
              memory: 64Mi
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "postgresql-operator"
