kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: postgresql-operator
subjects:
- kind: ServiceAccount
  name: postgresql-operator
  # Replace this with the namespace where the operator will be deployed.
  namespace: postgresql-operator
roleRef:
  kind: ClusterRole
  name: postgresql-operator
  apiGroup: rbac.authorization.k8s.io
